CREATE TABLE [SAMCO].[BB_SEC_Journal] (
    [REQUEST_DATETIME]  DATETIME2 (7)  NULL,
    [JOURNAL_DATETIME]  DATETIME2 (7)  NULL,
    [JOURNAL_OPERATION] NVARCHAR (MAX) NULL,
    [ID]                FLOAT (53)     NULL
);

