CREATE TABLE [SAMCO].[FXALL_TRADEDATA_ALLOCATIONS] (
    [CUSTOMER_ALLOCATION_ID]     VARCHAR (50)   NULL,
    [FXALL_TRADE_ID_SOURCE]      VARCHAR (50)   NULL,
    [ORDER_ID]                   VARCHAR (80)   NULL,
    [ACCOUNT]                    VARCHAR (121)  NULL,
    [SPOT_RATE]                  FLOAT (53)     NULL,
    [FORWARD_POINTS]             FLOAT (53)     NULL,
    [ALL_IN_RATE]                FLOAT (53)     NULL,
    [INDICATIVE_RATE]            FLOAT (53)     NULL,
    [COUNTERPARTY]               VARCHAR (30)   NULL,
    [CUSTOMER_USER_NAME]         VARCHAR (30)   NULL,
    [CURRENCY_PAIR]              VARCHAR (10)   NULL,
    [DEAL_DIRECTION]             VARCHAR (4)    NULL,
    [DEAL_AMOUNT]                FLOAT (53)     NULL,
    [DEALT_CURRENCY]             VARCHAR (4)    NULL,
    [VALUE_DATE]                 INT            NULL,
    [TRADE_DATE]                 INT            NULL,
    [DEAL_DATE]                  INT            NULL,
    [DEAL_TIME]                  VARCHAR (14)   NULL,
    [TENOR]                      VARCHAR (30)   NULL,
    [SOURCE_ID]                  VARCHAR (30)   NULL,
    [REMARKS]                    VARCHAR (1000) NULL,
    [CONTRA_AMOUNT]              FLOAT (53)     NULL,
    [FIXING_DATE]                INT            NULL,
    [TRANSACTION_TYPE]           VARCHAR (128)  NULL,
    [ACCOUNT_GROUP]              VARCHAR (128)  NULL,
    [USER_DEFINED_FIELD_1_NAME]  VARCHAR (38)   NULL,
    [USER_DEFINED_FIELD_1_VALUE] VARCHAR (128)  NULL,
    [UDF_2_NAME]                 VARCHAR (38)   NULL,
    [UDF_2_VALUE]                VARCHAR (128)  NULL,
    [UDF_3_NAME]                 VARCHAR (38)   NULL,
    [UDF_3_VALUE]                VARCHAR (128)  NULL,
    [UDF_4_NAME]                 VARCHAR (38)   NULL,
    [UDF_4_VALUE]                VARCHAR (128)  NULL,
    [UDF_5_NAME]                 VARCHAR (38)   NULL,
    [UDF_5_VALUE]                VARCHAR (128)  NULL,
    [UDF_6_NAME]                 VARCHAR (38)   NULL,
    [UDF_6_VALUE]                VARCHAR (128)  NULL,
    [UDF_7_NAME]                 VARCHAR (38)   NULL,
    [UDF_7_VALUE]                VARCHAR (128)  NULL,
    [UDF_8_NAME]                 VARCHAR (38)   NULL,
    [UDF_8_VALUE]                VARCHAR (128)  NULL,
    [UDF_9_NAME]                 VARCHAR (38)   NULL,
    [UDF_9_VALUE]                VARCHAR (128)  NULL,
    [UDF_10_NAME]                VARCHAR (38)   NULL,
    [UDF_10_VALUE]               VARCHAR (128)  NULL,
    [UDF_11_NAME]                VARCHAR (38)   NULL,
    [UDF_11_VALUE]               VARCHAR (128)  NULL,
    [UDF_12_NAME]                VARCHAR (38)   NULL,
    [UDF_12_VALUE]               VARCHAR (128)  NULL,
    [ALLOCATION_UTI]             VARCHAR (50)   NULL,
    [LEG_UPI]                    VARCHAR (10)   NULL,
    [CUSTOMER_ACCOUNT_LEI]       VARCHAR (30)   NULL,
    [PROVIDER_BRANCH_LEI]        VARCHAR (30)   NULL,
    [TRADING_DATE_TIME]          DATETIME       NULL,
    [VENUE]                      VARCHAR (4)    NULL,
    [ISIN]                       VARCHAR (12)   NULL,
    [WAIVER_INDICATOR]           VARCHAR (10)   NULL,
    [TRADING_CAPACITY]           VARCHAR (10)   NULL,
    [BENC_INDICATOR]             VARCHAR (4)    NULL,
    [NPFT_INDICATOR]             VARCHAR (4)    NULL,
    [ILQD_INDICATOR]             VARCHAR (4)    NULL,
    [OPERATION_TYPE]             VARCHAR (10)   NULL,
    [TPAC_INDICATOR]             VARCHAR (4)    NULL,
    [SEC_FIN]                    VARCHAR (1)    NULL,
    [SUBMIT_TIMESTAMP]           VARCHAR (50)   NULL,
    [EXECUTION_METHOD]           VARCHAR (10)   NULL,
    [PB_ACCOUNT]                 VARCHAR (50)   NULL,
    [LINK_ALLOCATION_ID]         INT            NULL,
    [SYSTEM_ID]                  VARCHAR (50)   NULL,
    [ACCOUNT_LONG_NAME]          VARCHAR (100)  NULL,
    [NUM_LOSING_BIDS]            SMALLINT       NULL,
    [BBAIM_ORDER_NR]             INT            NULL,
    [BBAIM_CLIENT_ORDER_ID]      VARCHAR (80)   NULL,
    [BBAIM_DEAL_SIDE]            VARCHAR (80)   NULL,
    [SCD_MANDATE]                VARCHAR (20)   NULL,
    [BBAIM_ACCOUNT]              VARCHAR (50)   NULL,
    [FXALL_TRADE_ID]             INT            NULL,
    [CONFORMED_FILE_NAME]        VARCHAR (100)  NULL,
    [ORDER_ALLOCATION_ID]        AS             ((((CONVERT([varchar](80),[BBAIM_ORDER_NR])+'-')+[BBAIM_DEAL_SIDE])+'-')+[SCD_MANDATE])
);

