CREATE TABLE [SAMCO].[FXGO_TRADEDATA_COMPETINGQUOTES] (
    [BBAIM_ORDER_NR]        INT           NULL,
    [BBAIM_CLIENT_ORDER_ID] VARCHAR (80)  NULL,
    [BBAIM_DEAL_SIDE]       VARCHAR (80)  NULL,
    [SCD_MANDATE]           VARCHAR (20)  NULL,
    [BBAIM_ACCOUNT]         VARCHAR (50)  NULL,
    [FXGO_TRADE_ID]         INT           NULL,
    [COMPQUOTE]             FLOAT (53)    NULL,
    [COMPDEALCODE]          VARCHAR (20)  NULL,
    [CONFORMED_FILE_NAME]   VARCHAR (100) NULL,
    [ORDER_ALLOCATION_ID]   AS            ((((CONVERT([varchar](80),[BBAIM_ORDER_NR])+'-')+[BBAIM_DEAL_SIDE])+'-')+[SCD_MANDATE])
);

