CREATE TABLE [SAMCO].[FXGO_TRADEDATA_ALLOCATIONS] (
    [MSGTYPE]                          VARCHAR (30)  NULL,
    [FXGO_TRADE_ID]                    INT           NULL,
    [LEGNUM]                           INT           NULL,
    [DEALTYPE]                         INT           NULL,
    [AMOUNT]                           FLOAT (53)    NULL,
    [CURRENCY]                         VARCHAR (10)  NULL,
    [ACCOUNT]                          VARCHAR (50)  NULL,
    [PBNAME]                           VARCHAR (50)  NULL,
    [UTI_PREFIX]                       VARCHAR (20)  NULL,
    [UTI_ID]                           VARCHAR (50)  NULL,
    [EXTERNAL_REFERENCE_ID]            VARCHAR (100) NULL,
    [FXGO_DEAL_SIDE]                   VARCHAR (10)  NULL,
    [PURE_DEAL]                        INT           NULL,
    [SIDE]                             VARCHAR (10)  NULL,
    [PRODUCT]                          INT           NULL,
    [TRANS_TYPE]                       INT           NULL,
    [REVISE_VER]                       INT           NULL,
    [BATCH_ID]                         INT           NULL,
    [TRADER_ID]                        INT           NULL,
    [TRADER_NAME]                      VARCHAR (40)  NULL,
    [COUNTERPARTY_UUID]                INT           NULL,
    [COUNTERPARTY_NAME]                VARCHAR (40)  NULL,
    [DATE_OF_DEAL]                     INT           NULL,
    [TIME_OF_DEAL]                     INT           NULL,
    [TRADE_DATE]                       INT           NULL,
    [DATE_CONFIRMED]                   INT           NULL,
    [TIME_CONFIRMED]                   INT           NULL,
    [BANK_1_DEALING_CODE]              VARCHAR (20)  NULL,
    [BANK_1_NAME]                      VARCHAR (100) NULL,
    [USER_IDENT_1]                     VARCHAR (100) NULL,
    [USER_IDENT_2]                     VARCHAR (100) NULL,
    [USER_IDENT_3]                     VARCHAR (100) NULL,
    [USER_IDENT_4]                     VARCHAR (100) NULL,
    [BROKER_DEALING_CODE]              VARCHAR (20)  NULL,
    [BROKER_NAME]                      VARCHAR (100) NULL,
    [CURRENCY_1]                       VARCHAR (10)  NULL,
    [CURRENCY_2]                       VARCHAR (10)  NULL,
    [NEAR_AMT_DEALT]                   FLOAT (53)    NULL,
    [NEAR_CCY_DEALT]                   VARCHAR (10)  NULL,
    [NEAR_COUNTER_AMT]                 FLOAT (53)    NULL,
    [NEAR_COUNTER_CCY]                 VARCHAR (10)  NULL,
    [FWD_POINTS_NEAR]                  FLOAT (53)    NULL,
    [FAR_AMT_DEALT]                    FLOAT (53)    NULL,
    [FAR_CCY_DEALT]                    VARCHAR (10)  NULL,
    [FAR_COUNTER_AMT]                  FLOAT (53)    NULL,
    [FAR_COUNTER_CCY]                  VARCHAR (10)  NULL,
    [FWD_POINTS_FAR]                   FLOAT (53)    NULL,
    [SPOT_BASIS_RATE]                  FLOAT (53)    NULL,
    [DEPOSIT_RATE]                     FLOAT (53)    NULL,
    [DAY_COUNT_TYPE]                   VARCHAR (20)  NULL,
    [NEW_ROLL]                         VARCHAR (10)  NULL,
    [VOLUME_OF_INTEREST]               FLOAT (53)    NULL,
    [EXCHANGE_RATE_PERIOD_1]           FLOAT (53)    NULL,
    [VALUE_DATE_PERIOD_1_CURRENCY_1]   INT           NULL,
    [TENOR_PERIOD_1]                   VARCHAR (10)  NULL,
    [FIXING_DATE_PERIOD_1]             INT           NULL,
    [FIXING_SOURCE_PERIOD_1]           VARCHAR (30)  NULL,
    [SETTLE_CRNCY]                     VARCHAR (10)  NULL,
    [SWAP_RATE]                        FLOAT (53)    NULL,
    [EXCHANGE_RATE_PERIOD_2]           FLOAT (53)    NULL,
    [VALUE_DATE_PERIOD_2_CURRENCY_1]   INT           NULL,
    [TENOR_PERIOD_2]                   VARCHAR (10)  NULL,
    [FIXING_DATE_PERIOD_2]             INT           NULL,
    [FIXING_SOURCE_PERIOD_2]           VARCHAR (30)  NULL,
    [SPLIT_TENOR_CRNCY_1]              VARCHAR (10)  NULL,
    [SPLIT_VALUE_DATE_CRNCY_1]         INT           NULL,
    [SPLIT_TENOR_CRNCY_2]              VARCHAR (10)  NULL,
    [SPLIT_VALUE_DATE_CRNCY_2]         INT           NULL,
    [COMMENT]                          VARCHAR (300) NULL,
    [NoteName_1]                       VARCHAR (100) NULL,
    [NoteText_1]                       VARCHAR (100) NULL,
    [NoteName_2]                       VARCHAR (100) NULL,
    [NoteText_2]                       VARCHAR (100) NULL,
    [NoteName_3]                       VARCHAR (100) NULL,
    [NoteText_3]                       VARCHAR (100) NULL,
    [NoteName_4]                       VARCHAR (100) NULL,
    [NoteText_4]                       VARCHAR (100) NULL,
    [NoteName_5]                       VARCHAR (100) NULL,
    [NoteText_5]                       VARCHAR (100) NULL,
    [PORTFOLIO]                        VARCHAR (100) NULL,
    [ALOC_ACCOUNT]                     VARCHAR (100) NULL,
    [ALOC_DESCRIPTION]                 VARCHAR (100) NULL,
    [ALOC_CUSTODIAN]                   VARCHAR (50)  NULL,
    [ALOC_PB_NAME]                     VARCHAR (50)  NULL,
    [REFERENCE_RATE_SPOT]              FLOAT (53)    NULL,
    [REFERENCE_RATE_PERIOD_1]          FLOAT (53)    NULL,
    [REFERENCE_RATE_PERIOD_2]          FLOAT (53)    NULL,
    [PAY_CCY]                          VARCHAR (10)  NULL,
    [PAY_SWIFT]                        VARCHAR (150) NULL,
    [PAY_ACCT_NUM]                     VARCHAR (150) NULL,
    [PAY_BANK]                         VARCHAR (150) NULL,
    [PAY_BRANCH]                       VARCHAR (150) NULL,
    [PAY_BENEFICIARY]                  VARCHAR (150) NULL,
    [PAY_SPCL_INSTR]                   VARCHAR (300) NULL,
    [REC_CCY]                          VARCHAR (150) NULL,
    [REC_SWIFT]                        VARCHAR (150) NULL,
    [REC_ACCT_NUM]                     VARCHAR (150) NULL,
    [REC_BANK]                         VARCHAR (150) NULL,
    [REC_BRANCH]                       VARCHAR (150) NULL,
    [REC_BENEFICIARY]                  VARCHAR (150) NULL,
    [REC_SPCL_INSTR]                   VARCHAR (150) NULL,
    [MIDRATESPOT]                      VARCHAR (150) NULL,
    [MIDRATENEAR]                      VARCHAR (150) NULL,
    [MIDFWDPOINTNEAR]                  VARCHAR (150) NULL,
    [MIDRATEFAR]                       VARCHAR (150) NULL,
    [MIDFWDPOINTFAR]                   VARCHAR (150) NULL,
    [USI_NAMESPACE]                    VARCHAR (20)  NULL,
    [USI_ID]                           VARCHAR (50)  NULL,
    [USI_ID_NEAR]                      VARCHAR (50)  NULL,
    [USI_ID_SWAP]                      VARCHAR (50)  NULL,
    [DELIVERY_DATE]                    INT           NULL,
    [BANKNOTE_RATE_TYPE]               FLOAT (53)    NULL,
    [COMMISSION]                       FLOAT (53)    NULL,
    [EXECUTION_VENUE]                  VARCHAR (50)  NULL,
    [BROKER_UUID]                      VARCHAR (50)  NULL,
    [BROKER_DEALCODE]                  VARCHAR (20)  NULL,
    [GROUP_ID]                         VARCHAR (20)  NULL,
    [GROUP_TYPE]                       INT           NULL,
    [TRADE_METHOD]                     INT           NULL,
    [SUB_TYPE]                         INT           NULL,
    [EXEC_VENUE_LEI]                   VARCHAR (100) NULL,
    [ISIN_NEAR]                        VARCHAR (50)  NULL,
    [ISIN_FAR]                         VARCHAR (50)  NULL,
    [ISIN_SWAP]                        VARCHAR (50)  NULL,
    [EXEC_WITHIN_FIRM_GPI]             VARCHAR (50)  NULL,
    [EXEC_WITHIN_FIRM_SHORTCODE]       VARCHAR (50)  NULL,
    [INVEST_DEC_WITHIN_FIRM_GPI]       VARCHAR (50)  NULL,
    [INVEST_DEC_WITHIN_FIRM_SHORTCODE] VARCHAR (50)  NULL,
    [TRADING_CAPACITY]                 INT           NULL,
    [PACKAGE_ID]                       VARCHAR (70)  NULL,
    [PRETRADE_TRANSPARENCY_TYPE]       VARCHAR (70)  NULL,
    [PRETRADE_TRANSPARENCY_REASON]     VARCHAR (70)  NULL,
    [POSTTRADE_TRANSPARENCY_TYPE]      VARCHAR (70)  NULL,
    [POSTTRADE_TRANSPARENCY_REASON]    VARCHAR (70)  NULL,
    [COMMODITIES_D_INDICATOR]          INT           NULL,
    [SECURITIES_FINANCING_TRANSACTION] INT           NULL,
    [MAKER_ALGO_ID]                    VARCHAR (70)  NULL,
    [ORD_REG_TIMESTAMP]                VARCHAR (30)  NULL,
    [ORD_REG_TIMESTAMP_TYPE]           INT           NULL,
    [TRD_REG_TIMESTAMP]                VARCHAR (30)  NULL,
    [TRD_REG_TIMESTAMP_TYPE]           INT           NULL,
    [TRADE_REPORTING_INDICATOR]        VARCHAR (50)  NULL,
    [COUNTRY_OF_MEMBERSHIP]            VARCHAR (50)  NULL,
    [BBAIM_ORDER_NR]                   INT           NULL,
    [BBAIM_CLIENT_ORDER_ID]            VARCHAR (80)  NULL,
    [BBAIM_DEAL_SIDE]                  VARCHAR (80)  NULL,
    [SCD_MANDATE]                      VARCHAR (20)  NULL,
    [BBAIM_ACCOUNT]                    VARCHAR (50)  NULL,
    [CONFORMED_FILE_NAME]              VARCHAR (100) NULL,
    [ORDER_ALLOCATION_ID]              AS            ((((CONVERT([varchar](80),[BBAIM_ORDER_NR])+'-')+[BBAIM_DEAL_SIDE])+'-')+[SCD_MANDATE])
);

