CREATE TABLE [SAMCO].[SCD_FXTRANSACTIONDATA] (
    [TRANSACTION_NO]                       BIGINT        NOT NULL,
    [PARTY]                                VARCHAR (100) NULL,
    [NOMINAL]                              FLOAT (53)    NULL,
    [FORWARD_RATE]                         FLOAT (53)    NULL,
    [SECURITY_ID]                          VARCHAR (100) NULL,
    [BUY_CCY]                              VARCHAR (3)   NULL,
    [BUY_NOMINAL]                          FLOAT (53)    NULL,
    [SELL_CCY]                             VARCHAR (3)   NULL,
    [SELL_NOMINAL]                         FLOAT (53)    NULL,
    [TRADE_DATE]                           DATE          NOT NULL,
    [AGREEMENT_TIME_STAMP]                 DATETIME      NULL,
    [INSTRUMENT_TYPE]                      VARCHAR (50)  NULL,
    [SETTLEMENT_DATE]                      DATE          NULL,
    [LEG_NO]                               INT           NULL,
    [LEG_NO1]                              INT           NULL,
    [BUSINESS_TRANS_CODE]                  VARCHAR (50)  NULL,
    [MATURITY_DATE]                        DATE          NULL,
    [PMT_DATE]                             DATE          NULL,
    [FX_SWAP_REFERENCE]                    INT           NULL,
    [FX_DEAL_TYPE_FROM_STATIC_DATA]        VARCHAR (50)  NULL,
    [CURRENT_VALUE_PC_L1]                  FLOAT (53)    NULL,
    [CURRENT_VALUE_QC_L1]                  FLOAT (53)    NULL,
    [CURRENT_VALUE_PC_L2]                  FLOAT (53)    NULL,
    [CURRENT_VALUE_QC_L2]                  FLOAT (53)    NULL,
    [PORTFOLIO_GROUP]                      VARCHAR (50)  NULL,
    [PORTFOLIO]                            VARCHAR (50)  NULL,
    [CURRENCY_CROSS]                       VARCHAR (10)  NULL,
    [FX_TICS]                              FLOAT (53)    NULL,
    [ALT_INV__EVENTS]                      VARCHAR (50)  NULL,
    [TURNOVER]                             FLOAT (53)    NULL,
    [TURNOVER_USD]                         FLOAT (53)    NULL,
    [TRANSACTION_NO_IN_ORIGINATING_SYSTEM] BIGINT        NULL,
    [TRADER]                               VARCHAR (50)  NULL,
    [PORTFOLIO_MANAGER]                    VARCHAR (50)  NULL,
    [BBAIM_DEAL_SIDE]                      VARCHAR (80)  NOT NULL,
    [BBAIM_ORDER_NR]                       INT           NOT NULL,
    [BBAIM_TICKET_NR]                      INT           NOT NULL,
    [SCD_MANDATE]                          VARCHAR (20)  NOT NULL,
    [CONFORMED_FILE_NAME]                  VARCHAR (100) NULL,
    [ORDER_ALLOCATION_ID]                  AS            ((((CONVERT([varchar](80),[BBAIM_ORDER_NR])+'-')+[BBAIM_DEAL_SIDE])+'-')+[SCD_MANDATE])
);

