CREATE ROLE [SAMCO_ROLE_USERS_TT]
    AUTHORIZATION [db_owner];


GO
ALTER ROLE [SAMCO_ROLE_USERS_TT] ADD MEMBER [Ruben.vanLierop@shell.com];


GO
ALTER ROLE [SAMCO_ROLE_USERS_TT] ADD MEMBER [Raymond.Wolswijk@shell.com];


GO
ALTER ROLE [SAMCO_ROLE_USERS_TT] ADD MEMBER [j.kok@shell.com];


GO
ALTER ROLE [SAMCO_ROLE_USERS_TT] ADD MEMBER [Ben.reterink@shell.com];


GO
ALTER ROLE [SAMCO_ROLE_USERS_TT] ADD MEMBER [eugene.gullit@shell.com];

