
CREATE     VIEW [SAMCO_TT].[VW_ORDER_ALLOCATION] AS
SELECT  DISTINCT [TSORDNUM] AS BBAIM_ORDER_NR, BBAIM_DEAL_SIDE , SCD_MANDATE,  CAST(TSORDNUM AS VARCHAR(30)) + '-' + BBAIM_DEAL_SIDE + '-' + SCD_MANDATE
 AS ORDER_ALLOCATION_ID from SAMCO.BBAIM_AUDITFEED